{%- if dev_language == 'R and Python' -%}
FROM docker.io/jupyter/datascience-notebook:r-4.3.1
{%- elif dev_language == 'Python' -%}
FROM docker.io/jupyter/scipy-notebook:python-3.11.6
{%- elif dev_language == 'R' -%}
FROM docker.io/jupyter/r-notebook:r-4.3.1
{%- endif %}

USER root

### System dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        lmodern file curl tmux && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/* /tmp/library-scripts

{% if use_quarto %}
### Quarto
# versions: https://quarto.org/docs/download/_download.json
# neat setup: https://github.com/jeremiahpslewis/reproducibility-with-quarto
ENV QUARTO_VERSION 1.3.450
RUN curl --silent -L --fail \
        https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb > /tmp/quarto.deb && \
    apt-get update && \
    apt-get install -y --no-install-recommends /tmp/quarto.deb && \
    rm -rf /tmp/quarto.deb /var/lib/apt/lists/* /tmp/library-script
{%- endif %}

USER ${NB_USER}

### R development
RUN pip install radian && \
    R -q -e 'install.packages(c("markdown", "languageserver", "httpgd"), repos="cloud.r-project.org")' &&\
    R -q -e 'remotes::install_github("ManuelHentschel/vscDebugger")'

### Prints Jupyter server token when terminal is opened
RUN echo "echo \"Jupyter server token: \$(jupyter server list 2>&1 | grep -oP '(?<=token=)[[:alnum:]]*')\"" > ${HOME}/.get-jupyter-url.sh && \
    echo "sh \${HOME}/.get-jupyter-url.sh" >> ${HOME}/.bashrc

RUN pip install jupyterlab-quarto

USER root

## BELOW DOES NOT WORK
## Adapted from https://github.com/UCSB-PSTAT/base-rstudio/blob/main/Containerfile
## Install rstudio from source package
RUN apt update -qq && \
    apt install software-properties-common -y && \
    add-apt-repository ppa:nrbrtx/libssl1 && \
    apt update -qq && \
    apt upgrade -y && \
    apt install -y \
        libssl-dev \
        libclang-dev \
        psmisc \
        libxkbcommon-x11-0 \
        libpq5 \
        lsb-release \
        && \
        apt-get clean

ENV R_STUDIO_VERSION 2023.06.1-524
RUN wget https://download1.rstudio.org/electron/jammy/amd64/rstudio-${R_STUDIO_VERSION}-amd64.deb && \
    wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-${R_STUDIO_VERSION}-amd64.deb && \
    apt install ./rstudio*.deb -yq && apt-get clean && rm -f ./rstudio*.deb && \
    apt-get clean 

RUN chmod 777 /var/run/rstudio-server && chmod +t /var/run/rstudio-server

USER ${NB_USER}

RUN mamba install -y -c conda-forge --freeze-installed jupyter-server-proxy jupyter-rsession-proxy && \
    mamba clean --all

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends tree && \
    rm -rf /var/lib/apt/lists/*
